spring:
  application:
    name: article-service
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    clear-checksums: true

  datasource:
    url: jdbc:postgresql://localhost:8081/pravda
    username: pravda
    password: pravda
    driver-class-name: org.postgresql.Driver

locale:
  default-locale: sr-Cyrl
  supported:
    - sr-Cyrl
    - sr-Latn

server:
  servlet:
    context-path: /api

application:
  frontend:
    url: "http://localhost:3001"
    revalidate-secret: "your_chosen_secret_password"
  security:
    google:
      client-id:
    jwt:
      secret-key:
      expiration: 900000 # 15 minutes
      refresh-token:
        expiration: 21600000 # 6 hours
      cookie:
        secure: false
        domain: null
  s3:
    access-key: mock
    secret-key: mock
    endpoint: fsn1.your-objectstorage.com
    region: eu-central
    bucket: pravda-images
  imgproxy:
    url: "http://localhost:8082"